apiVersion: 1
contactPoints:
    - orgId: 1
      name: Telegram alerts
      receivers:
        - uid: ff2b53sjb1a0we
          type: telegram
          settings:
            bottoken: 7943147593:AAHq0ziL_sXmlKqgEpOPleB9B9DBuxhmW-4
            chatid: "-4989862147"
            disable_notification: false
            disable_web_page_preview: false
            protect_content: false
          disableResolveMessage: false
